[package]
name = "succinct-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"

[dev-dependencies]
anyhow = "1.0.50"
pretty_assertions = "1.0.0"

