name: Unit Tests
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: "Tests"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          # Linux
          - { os: ubuntu-latest, toolchain: stable, target: x86_64-unknown-linux-gnu, cross: false }
          # Macos
          - { os: macos-11, toolchain: stable, target: x86_64-apple-darwin, cross: false }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Cache Rust
        uses: Swatinem/rust-cache@v1

      - name: Run test
        uses: actions-rs/cargo@v1
        with:
          command: test
          components: rustfmt
          args: --all-features --no-fail-fast
        env:
          RUST_TEST_THREADS: 2
          RUST_LOG: debug
          RUST_BACKTRACE: full
          CARGO_INCREMENTAL: '1'
          # RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests'
          # RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests'

      # - name: Install grcov
      #   run: cargo install --locked grcov

      # - name: Run code coverage
      #   uses: actions-rs/grcov@v0.1.5
      #   id: coverage

      # - name: Upload to codecov.io
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ${{ steps.coverage.outputs.report }}

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   if: failure()
      #   with:
      #     path: |
      #       _local_fs/
      #       _logs/
      #       _meta/
      #       metasrv/_logs/
      #       query/_logs/
      #       store/_logs/
